### ISSUE TITLE
fold this repo back into cellranger-aws-pipeline

### ISSUE THREAD

**Issue by ryan-williams** [ismms-himc/cellranger-aws-pipeline-rebuild#1]
This repo has sprawled to include:
* docs and scripts about setting up AWS
* docs and scripts about running pipelines
* docs and scripts about testing on tiny-bcl

I think we should fold it all into appropriate subfolders or branches on [ismms-himc/cellranger-aws-pipeline](https://github.com/ismms-himc/cellranger-aws-pipeline), continue using /issues there as our issue tracker, etc.

We don't need a separate repo about running tiny-bcl, and this is no longer about that anyway. This is more of updated docs and potential "v2" of that repo.

**Comment by cornhundred** [comment]
@ryan-williams see https://github.com/ismms-himc/cellranger-aws-pipeline/issues/8#issuecomment-529521791 

Let me know what you think

**Comment by ryan-williams** [comment]
added this as a submodule of the other one, seems close enough
